local wbjName, WBJ = ...;
local L = WBJ.L;

local puns = {  
    "My wife said to me that\nif I go fishing once more\nshe will leave me...\n\nGod I will miss her", "This scampi happening!",
    "\"So a fish walked into\na bar and said...\"\n\n\"Aw, don't be silly,\nfish can't talk\"", "Waiting with baited breath...",
    "Yes officer, I got me a licence.\nIt's for two days and I only\nused it once last week", "Goby with your\nfriends then...",
    "Is it dangerous to swim\non a full stomach?\n\nYes. It's better to swim\nin the water", "Why do clownfish taste so funny?",
    "Why are some fish at\nthe bottom of the ocean?\n\nBecause they dropped\nout of school", "So, fish bath in\na river basin?",
    "Did you hear about the fight\nat the seafood restaurant?\n\nFour fish got battered!", "Allah us wanna go\nfishing, wudhu?",
    "Teach a man to fish\nand he will sit in a\nboat all day and be\nlate for dinner...", "Don't carp on about it,\nplease %p!",
    "Why is a fishmonger\nnever generous?\n\nBecause his business\nmakes him shell-fish", "The early worm\ncatches the fish...",
    "What did the Atlantic Ocean\nsay to the Pacific Ocean?\n\nNothing, it just waved", "Fish that swim in\nschools are smart!",
    "Oh cod, I can't\ntake any more of\nthese fishy puns...\n\nI'm outta this plaice", "What you say is a\nload of scallops...",
    "Hmmm... not enough bass", "Oh, so you are supposed to\nwear a leather jacket...", "Were you expecting\njust a sole reply?",
    "What do you call a shark\nwith a rocket launcher?\n\nAnything it tells you to", "Where do fish sleep?\n\nIn the river bed",
    "What should you do if you\nfind a shark in your bed?\n\nSleep somewhere else", "I think the waiter sprat\nin your soup...",
    "I don't always make fish puns.\nBut when I do,...\nI do it for the halibut!", "Don't trout yourself!\nAny fin is possible",
    "Why did the plaice\ngo to the doctor?\n\nBecause he was\nfeeling a bit flat", "Football is a game\nbut fishing is serious",
    "What should you do if you\nfind a shark in your bed?\n\nSleep elsewhere...", "Question %p, do fish\nsleep in a river bed?",
    "What do you call a shark\nwith a machine gun?\n\nAnything he tells you to", "Where is a fish in orbit?\n\Trouter space...",
    "What happens to\nsleepy fish at the\nedge of a reef?\n\nThey drop off", "What do you call a\nshark with a gun?\n\n\"Sir\"",
    "Why did the fish\ncross the road?\n\nBecause the chicken\nwas on holidays", "Do you catch a Left Shark\nwith a left hook?",
    "What do you call\na deaf pike?\n\nAnything you like,\nhe cannot hear you", "Had a girlfriend, I lobster.\nThen I flounder",
    "Why are fish so gullible?\nThey fall for things\nhook, line and sinker!", "Work is for people who\ndon't know how to fish",
    "What do you call a\ndeaf great white shark?\n\nAnything you like...", "Old fishermen never die.\nThey just smell that way",
    "Why did the fish\ncross the road?\n\nIt was the chicken’s day off", "What kind of fish does\na parrot sit on?\n\nA perch!",
    "Do fish go home and brag\nabout the size of the bait\nthey stole?", "There's definitely something\nfishy here offisher...",
    "We're a fair way out...\nyou got enough fuel?\n\nI think so...", "What fish goes up the\nriver at 100mph?\n\nA motor-pike",		
    "What did the mermaid wear\nto maths class?\n\nHer algae-bra...", "When fish go into business\nthey start on a small scale",
    "Floundering about\nagain %p?", "Can we eel our\nrelationship?", "What kind of fish is made\nof two sodium atoms?\n\n2 na!", 
    "Early to bed,\nEarly to rise,\nFish all day,\nTell big lies", "Where did Noah keep the fish?\n\nIn a multi-level carp ark",
    "Seal 1: So this fish said to...\n\nSeal 2: Aww, don't be sealy,\nfish can't talk!", "I reely feel gillty", "DND: Fishing!",
    "I spent most of my\nmoney on fishing.\nThe rest I wasted", "I smell something fishy\naround here...", "You sealy doofish!",
    "What side of a fish\nhas the most scales?\n\nThe outside", "How do you\npost a fish?\n\nSend it COD", "AFK: Gone fishing!",
    "You okay %p? You seem\nto be floundering...", "Pollocks to you,\nyou basstard!", "I used to do that\nwhen I first started",
    "You should spend a few\nsquid on a new fishing hat", "Don't make the same\nmis-hake %p!", "I thought YOU put the plug in?",
    "Are you the new squid\non the block?", "Hmmm, your fishing\ngear should really\nscale well %p...", "Just one more cast...",
    "Wasn't your rod in the\nrod holder just now?", "I thought YOU were\ngoing to bring the bait!", "You're kraken me up %p...",
     "So I said to Nemo\n\"Don't be a clown...\"", "Careful, you'll pull a\nmussel doing that!", "Oops, my fly has\ncome undone",
    "There I was, pole in hand\nwith fishnets and eels on...", "Ah, sole is over there!", "Not tonight, I've\ngot a haddock...",
    "It is not the rod in the hand,\nbut the hand on the rod", "Time to scale back\non the fish puns", "It tugs on your fly...",
    "How do you communicate\nwith a fish?\n\nDrop it a line", "Good things come to\nthose that bait", "Any fin could happen...",
    "How can a fish\ncross the road?\n\nTie it to a chicken", "This plaice is great\nfor fishin'...", "Goin' in for the krill?",
    "Aww, the cute little fish\nare going to plaice school", "Don't drink from\nthe chum bucket!", "So saury, so very saury...",
    "Where do fish\nkeep their money?\n\nIn the river bank", "Uhoh... the fuel gauge is stuck...", "Thanks for all the fish...",
    "Did you just\nwee in the water?\n\nNo, the sea weed", "They always bite better\nyesterday", "Not bad, cod do batter %p...",
    "Hooked on fishin'!", "Who let you off the hook?", "Exactly how do\nyou jump a shark?", "So I guess you are\noff the hook?",
    "What do you use\nto cut the ocean?\n\nA sea-saw", "Can you sing without\nan autotuna?", "Oh cod, you are\nso shellfish...",
    "Hey, that lure I bought\ndidn't have a bar cod!", "Did you fart?\nBecause that sure smelt?", "One more and we'll have one",
    "Next time you're in Shatt,\ndrop me a line!", "At least it was a nice day on the water...", "Hey, where did my bobber go?",
    "Don't trout yourself!\nAny fin is possible!", "Stuck between a rock\nand a hard plaice...", "Let's not shark the issue...",
    "Reely? That's not what\nI've been herring!", "Well, just for the halibut of course...", "But what about the\nRight Shark?",		
    "Why did the fish\nswim to the river bank?\n\nBecause it couldn't walk", "Thank Cod it's Friday...", "That's eely nice %p!",
    "After a hard days fishing,\nthere's nothing like a\nglass of bitterling!", "Here's looking at\nyou, squid", "Carp diem...",
    "Keep friends close,\nanemones closer!", "Aw, c'mon %p,\ndon't be shellfish!", "I'm herring you %p...", "Don't be koi now!",
    "Fishing any day,\nbarramundi", "You seen my guitar tuna?", "So how do you tuna fish?", "Let minnow %p...", "Learn to sea!",
    "Murloc gear scales well!", "Why is your line slack?", "What a roeful idea...", "Just krilling time...", "That's no fluke!",
    "Yes officer, i do have a\nlot of fish but they don't\ncount against my limit as\nthey are very small...", "Seas the day!",
    "What is dry on the outside,\nfilled with water and\nblows up buildings?\n\nA fish tank", "Mullet over %p, mullet over...",
    "Whale, I best be off.\nIf you sea a friend,\ndon't forget to wave", "We all just need\nto clam down!", "Reely %p, reely?",
    "Ease up on the puns\nand keep it reel", "You are one bad\nmother puffer!", "Man I Love Fishing!", "You somebody's beach?", 
    "Make your own fish pun!\nDon't leave it to salmon else!", "Try salmon else %p...", "Good things come to\nthose who bait", 
    "You got anything to plug\nthis hole here?", "I'd rather be lucky than good!", "R.I.P. Laird!", "Whale you be mine?", 
    "You're my sole mate...", "We were manta be together", "My plaice or yours?", "Let's cuttle...",
    "Why be anemones when we could be special fronds?", "For my dar-Ling", "50 Shades of Greyling", "I caught you babe!",
    "You are my heart and sole", "You're a great catch %p", "I'm hooked on you!", "Let's hook up!",
    "Salmon-chanted evening with you", "It's o-fish-al!\nI want YOU to be\nmy valentine!",
}
WBJ.Puns = puns;
